### ISSUE TITLE
Allow aliases in cloudcannon.config.*

### ISSUE THREAD

**Issue by georgephillips** [CloudCannon/cloudcannon-jekyll#4]
I am using the following yaml:

```yaml
_editables:
  content: &toolbar
    width: 1180
    height: 900
    format: p h1 h2 h3 h4 h5 h6 div
    styles: /assets/cms-styles.css
    undo: true
    redo: true
    left: align-to-left
    center: align-to-center
    right: align-to-right
    justify: justify
    bold: true
    italic: true
    underline: true
    strike: true
    subscript: false
    superscript: false
    blockquote: true
    table: true
    copyformatting: true
    removeformat: true
    numberedlist: true
    bulletedlist: true
    outdent: false
    indent: false
    image: true
    link: true
    embed: true

_inputs:
  content_html:
    type: html
    options: *toolbar
  lower_text_html:
    type: html
    options: *toolbar
```

On cloudcannon this produces an error `Unknown alias: toolbar (Psych::BadAlias)` which is on this line:

https://github.com/CloudCannon/cloudcannon-jekyll/blob/c04b340dffd703d41497722bb9deb9146475ea44/lib/cloudcannon-jekyll/config.rb#L58

Aliases require a flag on safe_load:

```ruby
loaded = YAML.safe_load(File.read(path), aliases: true) # Also works for JSON
```
